on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:
name: Build book

env:
  isExtPR: ${{ github.event.pull_request.head.repo.fork == true }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v2

    - uses: r-lib/actions/setup-pandoc@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Build site
      run: |
        # Allows [implcit heading links] to work; will need to convert
        # to explicit before switching to visual editor
        options(bookdown.render.file_scope = FALSE)
        bookdown::render_book("index.Rmd")
      shell: Rscript {0}

    - name: Deploy to Netlify
      if: contains(env.isExtPR, 'false')
      id: netlify-deploy
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './_book'
        production-branch: first-ed-updates
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message:
          'Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})'
        enable-pull-request-comment: false
        enable-commit-comment: false
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1
